import { ResponseBanner } from "./types/BannerInterface";

export const exmpleBanner: ResponseBanner[] = [{
    author: "Admin",
    catogryID: "456",
    clickCount: 0,
    createdAt: "2023-11-22T07:27:33.633Z",
    image: {
        alt: "Banner 1",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7rBbw6FThUHGkWfi5_JGe0NpqN3p2XS2Rhw&usqp=CAU",
    },
    kind: ['price'],
    name: "Banner 1",
    productID: "123",
    size: "side",
    text: "Special Sale!",
    __v: 0,
    _id: "1",
}, {
    author: "John Doe",
    catogryID: "789",
    clickCount: 15,
    createdAt: "2023-11-23T09:45:21.123Z",
    image: {
        alt: "Awesome Banner",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4r5PwaOdp97FiCsbmhHThLusqv_vd9kWwRg&usqp=CAU",
    },
    kind: ['discount', 'sale'],
    name: "Special Offer",
    productID: "456",
    size: "large",
    text: "Limited Time Offer!",
    __v: 1,
    _id: "2",
}, {
    author: "Alice",
    catogryID: "101",
    clickCount: 8,
    createdAt: "2023-11-24T12:30:45.567Z",
    image: {
        alt: "Summer Sale",
        url: "https://www.tapet3d.co.il/files/products/product23_image1_2021-03-29_11-25-56.jpg",
    },
    kind: ['discount'],
    name: "Summer Sale",
    productID: "789",
    size: "medium",
    text: "Hot Deals for Summer!",
    __v: 2,
    _id: "3",
}, {
    author: "Bob",
    catogryID: "202",
    clickCount: 12,
    createdAt: "2023-11-25T15:20:30.789Z",
    image: {
        alt: "New Arrivals",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf5x5SoebRbIFuWZbuivoTVfAign9O9Iee0Q&usqp=CAU",
    },
    kind: ['new'],
    name: "New Arrivals",
    productID: "345",
    size: "large",
    text: "Discover Exciting New Products!",
    __v: 0,
    _id: "4",
}, {
    author: "Eve",
    catogryID: "303",
    clickCount: 5,
    createdAt: "2023-11-26T18:10:15.987Z",
    image: {
        alt: "Flash Sale",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZZKsULxS0Tdi9pG2_0--uQ-c46OnV8xaFxw&usqp=CAU",
    },
    kind: ['discount', 'limited-time'],
    name: "Flash Sale",
    productID: "567",
    size: "small",
    text: "Hurry! Limited Time Offers!",
    __v: 3,
    _id: "5",
}


]